version: '3'
services:
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    networks:
      - dev-network
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=kafka-broker
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-borker:29092
      # - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
      - DYNAMIC_CONFIG_ENABLED=true


networks:
  dev-network:
    external: true

volumes:
  kafka_data:
    driver: local
    
